### PR TITLE
Docker fix

### PR DESCRIPTION
**Pull request by jfirehammer-credibly**
The docker build failed as of today and the latest alpine release.
I made a best effort guess as to when the last build worked and rev-locked it.
Feel free to change the rev as needed if it's not what you want.

### CODE REVIEW

**Comment by PGBI** [comment]
On my side, I don't have any difficulty to build the docker image from the current master branch. What error do you get?

**Comment by jfirehammer-credibly** [comment]
So, there are a number of errors, but it starts with this and they cascade from it:

```
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/linux_musl-x64-47_binding.node": 

HTTP error 404 Not Found       
```

I am pretty sure it has to do with the 'latest' version of alpine on my production machine being an older version that was locally cached. (I just reproduced it again now). That's why it does not fail for you, and also does not fail for me on a different machine that had not yet downloaded alpine yet.

This is why I've found that it's always good to rev lock your dockerfiles. (I run all of my servers in docker and have run into this enough times that I always do it now!)

**Comment by PGBI** [comment]
I agree with you that rev-locking is a good practise. But I'd like to be able to reproduce the error. I completely removed all containers and images from my docker setup, and rebuild kong-dashboard image from scratch. It succeeded.

Also, on docker hub, a kong-dashboard image was built from the master branch 4 hours ago, without no problem. See the logs section on this page => https://hub.docker.com/r/pgbi/kong-dashboard/builds/bvwxpk2kqqpwcxddpbnanuh/

**Comment by jfirehammer-credibly** [comment]
Yes, it will succeed because if you remove all images, it will download the latest alpine which works fine. The problem is if, as in my case, the last time I built using alpine was awhile ago, the 'latest' on my machine is not the actual latest version. For example:

```
> docker images
mhart/alpine-node                     7.5.0               2f72775ebfff        5 weeks ago         53.47 MB
mhart/alpine-node                     latest              a5ba4d8acdbc        11 months ago       36.83 MB

>  sudo docker run mhart/alpine-node node --version
v5.10.1

```

So you can't reproduce the issue using your current dockerfile, but you can fake it by setting it to my version, e.g.

`FROM mhart/alpine-node:5.10.1
`

I just reproduced it that way myself on my newer machine.

Also FYI it appears that the latest as of right now is 7.7.2.

**Comment by PGBI** [comment]
Ok makes sense. I initially understood that all build were failing past a certain alpine version. Thanks for the explanation and the PR!

**Pull request merged**
