### PR TITLE
Add support for Kong admin API protected with key-auth

### PR DESCRIPTION
**Pull request by PGBI**

### CODE REVIEW

**Comment by balexandre** [comment]
@PGBI something must get lost in "translation" ... the current `3.0` branch does not have the same `readme` file as the [auth key part is missing](https://github.com/PGBI/kong-dashboard/pull/154/commits/bc1908b8df4924470c56bc98ac5289cea981abb3)

yep, you deleted it on your next commit (0e25b60) :(

**Comment by balexandre** [comment]
@PGBI ...

**Comment by PGBI** [comment]
I did, for consistency: --kong-username and --kong-password options aren't described for instance. I want to keep the readme file small, and not describe all auth possibilities.

**Comment by balexandre** [comment]
@PGBI that's personal opinion then... at least a "more authentications supported" link to a wiki entry, so it's not that hard to find how to.

**Comment by balexandre** [comment]
@PGBI when can you update npm so we can use this new authentication? 

just to avoid run it through source code :)

**Pull request merged**
