### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by Toilal**
I don't know if you are interested in docker, but this is a working dockerfile.

For some reason npm install doesn't work properly when using root, so i've created a kong-dashboard user inside the image.

To build: `docker build -t kong-dashboard .`

To run: `docker run -p 8080:8080 -it kong-dashboard`

If you merge this, could you then create an Automated build in docker hub ? For the image to be build on each git push ?

### CODE REVIEW

**Comment by PGBI** [comment]
@Toilal thanks for your PR. I'm not familiar with docker. I tested it and it looks great. Would you mind also updating the README.md file to describe the install process using docker?

**Comment by sinzone** [comment]
+1

**Comment by Toilal** [comment]
I've updated README.md

**Comment by PGBI** [comment]
:+1:

**Pull request merged**
