### PR TITLE
Adding Support for Kong 0.12. Upgrading to 4.0.0

### PR DESCRIPTION
**Pull request by peeyush1234**
Hi @PGBI ,

Please review and let me know if this change can be merged. This change adds support for Kong 0.12.

I ran all the tests and they passed.

Best,
Peeyush

### CODE REVIEW

**Comment by PGBI** [comment]
I wasn't planning on dropping support to Kong 0.9/0.10/0.11, but rather come up with Kong Dashboard v3.1.0 which would support Kong from version 0.9 to version 0.12.

I haven't taken a deep look at Kong 0.12 yet. Does its API have that many breaking changes that would justify a new major version of Kong Dashboard for Kong 0.12 only?

**Comment by peeyush1234** [comment]
Thanks for the quick response.

There is only one breaking change. In version 0.12, Kong has changed the endpoints for fetching 'active' and 'all' the targets for an upstream (https://getkong.org/docs/0.12.x/admin-api/#list-all-targets).

To avoid the major version upgrade, code here https://github.com/PGBI/kong-dashboard/blob/3.0/src/js/controllers/targets.js#L20 needs to be updated to have a conditional statement based on the Kong Version. Something like this will do:

`if (Kong_major_version > 0.11) {
    path = "..."
  } else {
    path = "..."
  }
`
I think this is a hacky solution.

Also, for Kong 0.12, in the docker-compose file you have to provide an environment config (https://github.com/peeyush1234/kong-dashboard/blob/4.0/docker-compose.yml#L47) KONG_ADMIN_LISTEN to ensure that Admin API is reachable via the host's interface. If you want to keep the same major version then I am not sure how I would add this config conditionally in docker-compose.

For these 2 reasons, I felt upgrading the version is the best thing to do.

Please let me know if you think otherwise.

**Comment by stmpy** [comment]
I am in need of support for v0.12 as well and would be willing to provide any assistance that is needed

Update: @peeyush1234 we have spun up a docker image from your build and walking through it

**Comment by peeyush1234** [comment]
@stmpy Thanks for trying the latest code. Let me know how it goes.

@PGBI Just wanted to check in if you have any other comments on the pull request.

**Comment by PGBI** [comment]
My initial comment remain: I'm not willing to drop support of Kong < 0.12. Given that there is only one breaking change in Kong 0.12, having a version 4.0.0 of Kong Dashboard isn't justified.

I had spent a lot of time to make Kong Dashboard 3.x.x compatible with multiple versions of Kong. I haven't done that to throw everything away once Kong 0.12 is available.

Logic such as `if (Kong_major_version > 0.11) { path = "..." } else { path = "..." }` may feel hacky, but between this and having to support 4 different versions of Kong Dashboard for 4 different versions of Kong, I prefer solution that solution. I just don't have the resources to maintain several branches of Kong Dashboard.

This being said, you can easily access the current Kong version in an angular controller. In case this was your issue, here is how to do it:
```
angular.module('app').controller("TargetsController", ["env", function (env) {
  env.kong_version; // 0.12.0
  ...
});
```

**Comment by peeyush1234** [comment]
Thanks for the response @PGBI . I will update the pull request to add support for Kong 0.12 in 3.1.0v kong-dashboard as you previously suggested.

**Comment by peeyush1234** [comment]
Closing in favor of https://github.com/PGBI/kong-dashboard/pull/149

**Pull request closed without merging**
